### ISSUE TITLE
Phone numbers need area codes (for touch-dialing)

### ISSUE THREAD

**Issue by jrosczyk** [ucsc/wcms-design-templates#356]
Cell phones will auto-detect phone numbers, but I'm noticing a lot of content editors in the wcms haven't included area codes to the phone numbers. This is required to be able to touch dial a phone number on a cell phone. (Below is an example. It's of course missing the 831 prefix.)
![unknown-4](https://cloud.githubusercontent.com/assets/1766496/4850584/f9038d2e-606a-11e4-8533-fa7bd337e746.png)
To fix this I'm suggesting, first: all content editors should be notified of this (hopefully they can correct most of them), and second: a jquery regex script should be written to add the missing area codes and also reformat the html into the proper phone anchor syntax.

**Comment by dajoturner** [comment]
We don't want to automate a fix (script for inserting the area codes), since we don't know what the area codes are. Needs to be training / communication to end users.
