### ISSUE TITLE
Update Home Page Data Def

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/wcms-design-templates#365]
Changes needed to allow for changes to billboard headlines incl. various color options
This needs to be changed for the large AND small home page types

**Comment by knice** [comment]
This has been done in dev and [documentation for the change is here](https://github.com/ucsc/wcms-design-templates/wiki/3-billboard-data-definition).

I'm going to close this ticket since the development work is done. If there are any issues with the DD, we can open a new ticket.
