### ISSUE TITLE
Normalize site titles

### ISSUE THREAD

**Issue by knice** [ucsc/wcms-design-templates#391]
Some site titles are `h1` and some are `p` and some are just `a`. Need to adjust the CSS written by RO to make sure all site titles are the same, regardless of their tags. 

Note: tags are different based on the page you are on. Every page needs an H1 for accessibility. Home pages have the site title in an H1, but interior pages have their main titles as the H1.

**Comment by teresasilva71** [comment]
Adding thoughts to this.
Crown College doesn't have any code to tell the site title how big to be and it's pretty small:
![site title](https://user-images.githubusercontent.com/7795841/35517931-d3808636-04c4-11e8-8713-aa91ce404f9e.jpg)
Admissions has <p class="title-xlarge"> and it's a normal size:
![site title1](https://user-images.githubusercontent.com/7795841/35517974-f077790c-04c4-11e8-8a1b-fc2859cddc42.jpg)

**Comment by teresasilva71** [comment]
And SocSci's title disappeared: 
![socsci title](https://user-images.githubusercontent.com/7795841/35520578-444dd33a-04cc-11e8-9829-290627f7bb15.jpg)

**Comment by knice** [comment]
I've normalized site titles for all HTML tags that occur in the site title area.

http://recordit.co/lL0KgfD4jP

(Ignore the h6 boldness. H6 never occurs in a site title)
