### ISSUE TITLE
Middle Row Content Blocks Smushed

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/wcms-design-templates#396]
![middle row](https://user-images.githubusercontent.com/7795841/35524575-d2f2512e-04d6-11e8-8e6c-1ad723701771.jpg)
See https://its-dev.ucsc.edu

**Comment by teresasilva71** [comment]
Here's another site with the middle row content actually overlapping:
![merrill middle row blocks](https://user-images.githubusercontent.com/7795841/35874541-96dcf10c-0b21-11e8-85ac-2539e4fac489.jpg)
https://merrill-dev.ucsc.edu

**Comment by knice** [comment]
A fix for this is implemented on stage. I tested ITS and Merrill.

**Comment by teresasilva71** [comment]
Reviewed. Looks resolved. Closing
