### ISSUE TITLE
Department Title Spacing?

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/wcms-design-templates#398]
Is there any way to reduce the amount of horizontal spacing above and below the department title? Seems way too roomy.
![title spacing](https://user-images.githubusercontent.com/7795841/35529531-2bff35ca-04e6-11e8-9693-2860f8598d34.jpg)

**Comment by knice** [comment]
This is resolved on dev. Take a look

**Comment by teresasilva71** [comment]
Much Better!!!
