### ISSUE TITLE
Class Schedule Feed- Colors

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/wcms-design-templates#399]
Do we want to address the colors from the feed for the Class Schedule pages?
![class schedule feed colors](https://user-images.githubusercontent.com/7795841/35530890-3b7056b6-04ea-11e8-8463-b8b28f9c33cf.jpg)

**Comment by knice** [comment]
I've fixed this in the CSS file, and it will go live when we launch. You won't see it on stage because all of the PHP pages on stage point the current **live** version of the `soc.css` file.

**Comment by knice** [comment]
This is resolved.
