### ISSUE TITLE
Left Nav Link colors

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/wcms-design-templates#401]
Colors for Left Nav items changes from blue to black...intentional or bug?
![left nav colors](https://user-images.githubusercontent.com/7795841/35874928-a7139a98-0b22-11e8-8e84-bdd2cb49ed6d.jpg)
![left nav colors1](https://user-images.githubusercontent.com/7795841/35874930-a73263ba-0b22-11e8-87df-be20c8f28e53.jpg)

**Comment by knice** [comment]
Yes, to indicate that is the **current** page. I've removed the underline though. So it is black without an underline to indicate the current page.
