### ISSUE TITLE
Site Title Size

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/wcms-design-templates#405]
...size of site title is too small, especially when compared to the billboard headline text. It should ~at least~ be the same size, if not bigger.
![site title](https://user-images.githubusercontent.com/7795841/37120334-f4b4c45e-220e-11e8-8070-05bc0e512f18.jpg)

**Comment by knice** [comment]
Closing this. Site titles are normalized to Rolling Orange's design specification.
