### ISSUE TITLE
Billboard Headline Spacing

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/wcms-design-templates#406]
Text in billboards is smashed against the left side of the image. Needs some padding.
![headline spacing](https://user-images.githubusercontent.com/7795841/37120439-4507e864-220f-11e8-817b-da1982ca451b.jpg)

**Comment by knice** [comment]
This was actually an issue with the billboard styles for horizontal layouts. I've fixed that issue on stage.

https://sociology-stage.ucsc.edu

![screen-2018-03-21-43510](https://user-images.githubusercontent.com/36719/37743154-f2fe2458-2d25-11e8-8adb-2c1e1b47b13c.png)
