### ISSUE TITLE
Tan block when using Div Class

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/wcms-design-templates#408]
I use the Div Class when I write FAQs. I use this to list topics that are anchored to sections on a page or link to another page. I am noticing that the Div Class areas are still tan. 

Web site is http://clp-dev.ucsc.edu

You can see this on the rightmost middle row content block and on every FAQ page. Example: 
http://clp-dev.ucsc.edu/faqs/catalog/index.html

**Comment by CorinneOC** [comment]
![div class tan clp website](https://user-images.githubusercontent.com/9750983/37181116-8da4bc56-22e0-11e8-8dde-7f3ca6862bbd.jpg)

**Comment by CorinneOC** [comment]
![div class on clp faq page](https://user-images.githubusercontent.com/9750983/37181151-b15fc352-22e0-11e8-9be0-a60092fe9996.jpg)

**Comment by knice** [comment]
Fixed in DEV and STAGE.

![screen-2018-03-08-30924](https://user-images.githubusercontent.com/36719/37181662-bf6c766e-22e2-11e8-91a2-237788b24431.png)

**Comment by CorinneOC** [comment]
Thanks! I did notice that when I added the callout-left full to my columns-2 it worked but if I don't have to change all my pages that would be preferred!

**Comment by CorinneOC** [comment]
So I am noticing that the majority of my Div areas now don't have shading and are just using ULs. For example see http://clp-dev.ucsc.edu/faqs/faculty/index.html 

It had Div blocks and now they are entirely gone. :( 

I'd rather have no fix then have those Div's gone. Please re-open the ticket

**Comment by CorinneOC** [comment]
Never mind. It's all good.
