### ISSUE TITLE
Top Nav Spacing

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/wcms-design-templates#411]
Can you decrease the space in between each top nav item? Seems a bit much. :)
![top nav](https://user-images.githubusercontent.com/7795841/37374064-a310c982-26d6-11e8-858d-3781e14816f4.jpg)

**Comment by thomasgardner** [comment]
Another site with this problem is https://clrc-preview-stage.ucsc.edu/
![screen shot 2018-03-20 at 3 29 12 pm](https://user-images.githubusercontent.com/1775933/37686239-bce9e406-2c53-11e8-912a-c0a12ce163e9.png)

**Comment by knice** [comment]
I have tightened them up a bit (just deployed to stage), but there will still be sites that break to two lines. Sites that have 7 or 8 nav items will most definitely break, but I seem to recall we've always discouraged more than 6 anyway.

I don't think there's anything more I can do on this one. We need navigation to be obvious, clear and visible, and main navigation links need to be far enough apart so people can discern between links.

**Comment by teresasilva71** [comment]
I think it's much better. CLRC has too many top nav items. I'm closing this one.
