### ISSUE TITLE
Tiled Directory Page Only Shows Up to 3 Columns

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/wcms-design-templates#417]
In production the tiled directory page shows up to 4 columns. In stage the tiled directory page shows a maximum of 3 columns. 
![tiled directory page 4 columns](https://user-images.githubusercontent.com/9750983/37738710-0e2c7ed4-2d15-11e8-9044-91fb268701f6.jpg)
![tiled directory page new design](https://user-images.githubusercontent.com/9750983/37738712-0e475e3e-2d15-11e8-9aec-f717e4733e85.jpg)

**Comment by knice** [comment]
Kate did the styles for the directory pages. The CSS for this page is in a file I don't have access to. @teresasilva71, can you let Kate know about this?

**Comment by knice** [comment]
It is back to four now. Tested in Chrome, Firefox, Safari, IE 11, and IE Edge.
