### ISSUE TITLE
Custom Code in Footer Block

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/wcms-design-templates#418]
arc.ucsc.edu has some custom HTML from addthis.com to allow folks to "Share"
Is there a workaround for them so they can keep this?
![footer-share](https://user-images.githubusercontent.com/7795841/37779843-993a610e-2daa-11e8-87cd-bd58e61c53a2.jpg)

**Comment by knice** [comment]
I'm going to close this. We won't be allowing custom code in footer blocks.
