### ISSUE TITLE
No Submit Button on Feedback Pages

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/wcms-design-templates#419]
https://urelations-stage.ucsc.edu/feedback.php
![feedback](https://user-images.githubusercontent.com/7795841/37795484-d264e3f6-2dd1-11e8-8e20-26b947f08713.jpg)

**Comment by knice** [comment]
If you view the source of the page, it's not complete. An error on the server is causing the rendering to halt and the browser is not getting the entire HTML source of the page.

I seem to recall this happening before, and it was related to PHP.

**Comment by teresasilva71** [comment]
Is that because it's on stage? @thomasgardner can you take a peek?

**Comment by knice** [comment]
Yeah, I think we've addressed this issue on DEV and PROD, but not STAGE.

**Comment by teresasilva71** [comment]
OK, We'll see what happens when we go live. Should be ok, right?

**Comment by teresasilva71** [comment]
fixed
