### ISSUE TITLE
Dept Title Font Issue

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/wcms-design-templates#422]
Font Probs:
![font prob](https://user-images.githubusercontent.com/7795841/37934806-571e7ec4-3104-11e8-95e3-a62d2fca5ec6.jpg)

**Comment by knice** [comment]
This is fixed. They had a `span` tag in their site title. I removed it. Site needs to be published.

**Comment by teresasilva71** [comment]
Done. Thanks.
