### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/wcms-design-templates#423]
From Jenna Scarpelli in astro.ucsc.edu
"One item - when you go to type in the search bar on the main page if you click in it doesn’t deleted the faint writing, you have to select all and delete then type your query. Kind of a pain."

**Comment by knice** [comment]
I just tested this on several sites and it works as expected. You click into the search field and as soon as you start typing, the placeholder text goes away. 

No deleting is necessary. I'm going to close this. If you find any other sites where this is happening, let me know.
