### ISSUE TITLE
University Relations staff directory page error

### ISSUE THREAD

**Issue by luckyluke007** [ucsc/wcms-design-templates#428]
Not publishable.
https://urelations.ucsc.edu/about/staff/index.php

![screen shot 2018-03-27 at 11 15 15 am](https://user-images.githubusercontent.com/1154568/37986394-2c55d4ce-31b0-11e8-8bf6-ae226120e4a8.png)

**Comment by knice** [comment]
Several folks have emailed about this. I didn't create the format for that page. It was part of the Directory project. I told Anissa to put a ticket in to see what is going on with that page.

**Comment by knice** [comment]
Nevermind. It is fixed. An ampersand in one of the user fields was causing the problem.
