### ISSUE TITLE
sans serif top nav

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/wcms-design-templates#429]
Rob, do you care if folks put in HTML to change the top nav font to a sans serif like Environmental Studies did? Also makes it MUCH bigger than other top navs.
Looks like they did it RIGHT after we rolled out the new designs.
I can contact the site managers asking about it if you want OR you can insert code to overwrite other people's shenanigans as in the past.
Let me know:
![sans serif](https://user-images.githubusercontent.com/7795841/38269534-a83ff10c-3735-11e8-82be-f01b7266c27d.jpg)

**Comment by knice** [comment]
Yup, this is not an appropriate change. I know some people don't like the serif typeface, but that is the standard. And frankly, it's part of the design. People are free to not like the design, but it needs to remain as is across the sites. The whole reason we have a WCMS is to create a consistent web presence for our users. 

I'ver added a line of javascript to `main.js` to strip style attributes. from main nav items. You might have to force-refresh your browser to load it.

**Comment by teresasilva71** [comment]
Snap! Taken care of. Thanks Rob. :)
